UI/Models/ConsignmentSummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UI.Models
{
    public class ConsignmentSummary
    {
        public int ConsignmentID { get; set; }

        public int ConsignorID { get; set; }

        public string Consignor { get; set; }

        public int ConsigneeID { get; set; }

        public string Consignee { get; set; }

        public DateTime BookingDate { get; set; }

        public int TransactionID { get; set; }

        public string BillityType { get; set; }

        public string Bookingreference { get; set; }

        public string BrookerDetails { get; set; }

        public DateTime BillDate { get; set; }

        public decimal ValueOfGoods { get; set; }

        public string TaxPaidBy { get; set; }

        public string From { get; set; }

        public string Too { get; set; }

        public string PaymentTerms { get; set; }

        public string EwayBillNo { get; set; }

        public DateTime EwayBillDate { get; set; }

        public int Distance { get; set; }

        public decimal Servicecharge { get; set; }

        public decimal Covercharge { get; set; }

        public decimal Packingcharge { get; set; }

        public decimal Price { get; set; }

        public string branch { get; set; }
    }
}

UI/Controllers/ConsignmentSummary/ConsignmentsummaryController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using UI.Models;

namespace UI.Controllers.ConsignmentSummary
{
    public class ConsignmentsummaryController : Controller
    {
        // GET: Consignmentsummary
        public async System.Threading.Tasks.Task<ActionResult> GetAllConsignmentDetails()
        {
            List<Models.ConsignmentSummary> consignment = new List<Models.ConsignmentSummary>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/ConsignmentSummary/GetAllConsignment"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    consignment = JsonConvert.DeserializeObject<List<Models.ConsignmentSummary>>(apiResponse);

                }
            }
            return View(consignment);
        }

        public async System.Threading.Tasks.Task<ActionResult> GetAllTransaction()
        {
            List<Models.GoodsTransactions> transaction = new List<GoodsTransactions>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/GoodsTransaction/GetAllGoodsTransaction"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    transaction = JsonConvert.DeserializeObject<List<GoodsTransactions>>(apiResponse);

                }
            }
            return View(transaction);
        }

        public async System.Threading.Tasks.Task<ActionResult> AddConsignmentsummary(int id)
        {
            Models.ConsignmentSummary consignment = new Models.ConsignmentSummary();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/ConsignmentSummaryID/GetconsignmentID?id=" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                   consignment = JsonConvert.DeserializeObject<Models.ConsignmentSummary>(apiResponse);

                }
            }
            return View(consignment);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> AddConsignmentsummary(Models.ConsignmentSummary summary)
        {
            if (ModelState.IsValid)
            {
                summary.branch = Session["Branch"].ToString();
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(summary), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync("http://localhost:17165/api/ConsignmentSummary/CreateConsignmentsummary", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        summary = JsonConvert.DeserializeObject<Models.ConsignmentSummary>(apiResponse);

                    }
                }

                TempData["SuccessMessage"] = "Record Saved Successfully";
                return RedirectToAction("GetAllConsignmentDetails");
            }

            return View();
        }


    }
}

UI/Controllers/GoodsTransaction/GoodTransactionController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using UI.Models;

namespace UI.Controllers.GoodsTransaction
{
    public class GoodTransactionController : Controller
    {

        
        // GET: GoodTransaction
        public async System.Threading.Tasks.Task<ActionResult> GoodTransactions()
        {
            //string user = Session["Username"].ToString();

            List<Models.GoodsTransactions> transaction = new List<GoodsTransactions>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/GoodsTransaction/GetAllGoodsTransaction"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    transaction = JsonConvert.DeserializeObject<List<GoodsTransactions>>(apiResponse);

                }
            }
            return View(transaction);
        }

        //public async System.Threading.Tasks.Task<List<ConsignorID>> PopulateConsignor()
        //{
        //    List<Models.ConsignorID> consignor = null;
        //    using (var httpClient = new HttpClient())
        //    {
        //        using (var response = await httpClient.GetAsync("http://localhost:17165/api/GoodsTransact/PopulateConsignor"))
        //        {
        //            string apiResponse = await response.Content.ReadAsStringAsync();
        //            consignor = JsonConvert.DeserializeObject<List<ConsignorID>>(apiResponse);
        //            ViewBag.Consignor = consignor;
        //        }
        //    }
        //    return consignor;
        //}

        //public async System.Threading.Tasks.Task<List<GoodsTransactions>> PopulateConsignee()
        //{
        //    List<Models.GoodsTransactions> transaction = new List<GoodsTransactions>();
        //    using (var httpClient = new HttpClient())
        //    {
        //        using (var response = await httpClient.GetAsync("http://localhost:17165/api/ConsigneeID/PopulateConsignee"))
        //        {
        //            string apiResponse = await response.Content.ReadAsStringAsync();
        //            transaction = JsonConvert.DeserializeObject<List<GoodsTransactions>>(apiResponse);

        //        }
        //    }
        //    return transaction;
        //}
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> CreateTransaction()
        {
            List<Models.ConsignorID> consignor = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/GoodsTransact/PopulateConsignor"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    consignor = JsonConvert.DeserializeObject<List<ConsignorID>>(apiResponse);
                    ViewBag.Consignor = consignor;
                }
            }

            List<Models.ConsigneeID> consignee = new List<ConsigneeID>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/ConsigneeID/PopulateConsignee"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    consignee = JsonConvert.DeserializeObject<List<ConsigneeID>>(apiResponse);
                    ViewBag.Consignee = consignee;

                }
            }
            //ViewBag.Consignor = PopulateConsignor(); ;
            return View();
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> CreateTransaction(Models.GoodsTransactions transaction)
        {
            if (ModelState.IsValid)
            {
                transaction.StaffID = Session["Username"].ToString();
                transaction.branch = Session["Branch"].ToString();
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(transaction), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync("http://localhost:17165/api/GoodsTransaction/CreateGoodsTransaction", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        transaction = JsonConvert.DeserializeObject<GoodsTransactions>(apiResponse);

                    }
                }

                TempData["SuccessMessage"] = "Record Saved Successfully";
                return RedirectToAction("GoodTransactions");
            }

            return View();
        }



    }
}

UI/Views/Consignmentsummary/AddConsignmentsummary.cshtml
@model UI.Models.ConsignmentSummary

@{
    ViewBag.Title = "AddConsignmentsummary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="page-header">
    <h2>Consignment Details</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-users"></i>
                </a>
            </li>
            <li><span>Consignments</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>


<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">Consignment Details</h2>
            </header>
            <div class="panel-body">

              @using (Html.BeginForm())
              {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                   
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                  
                            @Html.HiddenFor(model => model.ConsignorID, new { htmlAttributes = new { @class = "form-control" } })
                           
                    
                            @Html.HiddenFor(model => model.ConsigneeID, new { htmlAttributes = new { @class = "form-control" } })
                    
                    
                            @Html.HiddenFor(model => model.BookingDate, new { htmlAttributes = new { @class = "form-control" } })
                                         

                            @Html.HiddenFor(model => model.TransactionID, new { htmlAttributes = new { @class = "form-control" } })
                          

                    <div class="form-group">
                        @Html.LabelFor(model => model.BillityType, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select class="form-control" id="" name="BillityType">
                                <option>--Select--</option>
                                <option>GST INVOICE</option>
                                <option>Booking Challenge </option>
                            </select>
                            @Html.ValidationMessageFor(model => model.BillityType, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Bookingreference, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select class="form-control" id="" name="Bookingreference">
                                <option>Lagos</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.Bookingreference, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BrookerDetails, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select class="form-control" id="" name="BrookerDetails">
                                <option>Direct Customer</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.BrookerDetails, "", new { @class = "text-danger" })
                        </div>
                    </div>
                            @Html.HiddenFor(model => model.BillDate, new { htmlAttributes = new { @class = "form-control" } })
                           
                      

                    <div class="form-group">
                        @Html.LabelFor(model => model.ValueOfGoods, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ValueOfGoods, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ValueOfGoods, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TaxPaidBy, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select class="form-control" id="" name="TaxPaidBy">
                                <option>Consignor</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.TaxPaidBy, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Too, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Too, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Too, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PaymentTerms, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select class="form-control" id="" name="PaymentTerms">
                                <option>--Select--</option>
                                <option>Paid</option>
                                <option>To Pay</option>
                                <option>To Be Billed</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.PaymentTerms, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EwayBillNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EwayBillNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EwayBillNo, "", new { @class = "text-danger" })
                        </div>
                    </div>


                         @Html.HiddenFor(model => model.EwayBillDate, new { htmlAttributes = new { @class = "form-control" } })
                         


                    <div class="form-group">
                        @Html.LabelFor(model => model.Distance, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Distance, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Distance, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Servicecharge, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Servicecharge, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Servicecharge, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Covercharge, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Covercharge, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Covercharge, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Packingcharge, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Packingcharge, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Packingcharge, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
              }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>


            </div>
        </section>
    </div>
</div>

UI/Views/Consignmentsummary/GetAllConsignmentDetails.cshtml
@model IEnumerable<UI.Models.ConsignmentSummary>

@{
    ViewBag.Title = "GetAllConsignmentDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<header class="page-header">
    <h2>Consignment Details</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-users"></i>
                </a>
            </li>
            <li><span>Consignments</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>


<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <a href="@Url.Action("GetAllTransaction", "Consignmentsummary")" class="btn btn-primary">
                <i class="fas fa-plus-square"></i> Create
            </a>
        </div>
    </div>
</div>

<hr />


<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">Consignees</h2>
            </header>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Consignor)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Consignee)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ValueOfGoods)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.From)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Too)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.EwayBillNo)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Consignor)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Consignee)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ValueOfGoods)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.From)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Too)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EwayBillNo)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "EditConsignee", new { id = item.ConsignmentID }, new { @class = "btn btn-primary" })
                                    @Html.ActionLink("Delete", "DeleteConsignor", new { id = item.ConsignmentID }, new { @class = "btn btn-danger" })
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </section>

    </div>

</div>

@section Scripts
{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
        });
        @*function Delete(id) {
            alertify.confirm('Web Api CRUD Operations','Are You Sure to Delete this Record ?',function(){
                window.location.href  = '@Url.Action("Delete","Employee")/'+id;
            },null );
        }*@
    </script>


}

UI/Views/Consignmentsummary/GetAllTransaction.cshtml
@model IEnumerable<UI.Models.GoodsTransactions>

@{
    ViewBag.Title = "GetAllTransaction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<header class="page-header">
    <h2>Transactions</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-users"></i>
                </a>
            </li>
            <li><span>Transactions</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>


<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <a href="@Url.Action("CreateTransaction", "GoodTransaction")" class="btn btn-primary">
                <i class="fas fa-plus-square"></i> Create
            </a>
        </div>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">Transactions</h2>
            </header>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.TransactionID)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.GoodsID)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.GoodsDetails)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PackageType)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ShipmentType)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Consignorname)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ConsigneeNamee)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Weight)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Price)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.TrackingNumber)
                                </th>
                                <th></th>
                            </tr>
                        <thead>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TransactionID)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GoodsID)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GoodsDetails)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PackageType)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ShipmentType)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Consignorname)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ConsigneeNamee)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Weight)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Price)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TrackingNumber)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Create Summary", "AddConsignmentsummary", new { id = item.TransactionID }, new { @class = "btn btn-primary" })
                                    </td>
                                </tr>
                            }

                    </table>
                </div>
            </div>
        </section>

    </div>

</div>



@section Scripts
{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
        });
        @*function Delete(id) {
            alertify.confirm('Web Api CRUD Operations','Are You Sure to Delete this Record ?',function(){
                window.location.href  = '@Url.Action("Delete","Employee")/'+id;
            },null );
        }*@
    </script>


}