UI/Controllers/Consignee/ConsigneeController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using UI.Models;
namespace UI.Controllers.Consignors
{
    public class ConsigneeController : Controller
    {
        // GET: Consignee
        public async System.Threading.Tasks.Task<ActionResult> Consignee()
        {
            List<Recievers> consignee = new List<Recievers>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/Consignee/GetAllConsignee"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    consignee = JsonConvert.DeserializeObject<List<Recievers>>(apiResponse);

                }
            }
            return View(consignee);
        }

        public ActionResult CreateConsignee()
        {
            return View();
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> CreateConsignee(Models.Recievers reciever)
        {
            if (ModelState.IsValid)
            {
                reciever.branch = Session["Branch"].ToString();
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(reciever), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync("http://localhost:17165/api/Consignee/CreateConsignee", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        reciever = JsonConvert.DeserializeObject<Recievers>(apiResponse);

                    }
                }

                TempData["SuccessMessage"] = "Record Saved Successfully";
                return RedirectToAction("Consignee");
            }

            return View();
        }

        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> EditConsignee(int id)
        {
            Models.Recievers reciever = new Recievers();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/EditConsignor/GetConsigneeID?id=" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    reciever = JsonConvert.DeserializeObject<Recievers>(apiResponse);

                }
            }
            return View(reciever);
        }



    }
}

UI/Controllers/Consignor/MasterController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using UI.Models;

namespace UI.Controllers.Master
{
    public class MasterController : Controller
    {
        // GET: Master
        public async System.Threading.Tasks.Task<ActionResult> Consignors()
        {
            List<Consignor> consignor = new List<Consignor>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/Master/GetAllConsignor"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    consignor = JsonConvert.DeserializeObject<List<Consignor>>(apiResponse);

                }
            }
            return View(consignor);
        }

        //[HttpPost]
        //public async System.Threading.Tasks.Task<ActionResult> Consignors(string search)
        //{
        //    List<Consignor> consignor = new List<Consignor>();

        //    using (var httpClient = new HttpClient())
        //    {
        //        using (var response = await httpClient.GetAsync("http://localhost:17165/api/SearchConsignors/GetAllConsignor?search=" + search))
        //        {
        //            string apiResponse = await response.Content.ReadAsStringAsync();
        //            consignor = JsonConvert.DeserializeObject<List<Consignor>>(apiResponse);

        //        }
        //    }
        //    return View(consignor);
        //}

        public ActionResult CreateConsignor()
        {
            return View();
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> CreateConsignor(Models.Consignor consignor)
        {
            if (ModelState.IsValid)
            {
                consignor.branch = Session["Branch"].ToString();
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(consignor), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync("http://localhost:17165/api/Master/CreateConsignor", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        consignor = JsonConvert.DeserializeObject<Consignor>(apiResponse);

                    }
                }

                TempData["SuccessMessage"] = "Record Saved Successfully";
                return RedirectToAction("Consignors");
            }

            return View();
        }


        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> EditConsignor(int id)
        {
            Models.Consignor consignor = new Consignor();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:17165/api/Consignor/GetConsignorID?id=" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    consignor = JsonConvert.DeserializeObject<Consignor>(apiResponse);

                }
            }
            return View(consignor);
        }
        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> EditConsignor(Models.Consignor consignor)
        {
            if (ModelState.IsValid)
            {
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(consignor), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PutAsync("http://localhost:17165/api/Master/UpdateConsignor", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        consignor = JsonConvert.DeserializeObject<Consignor>(apiResponse);

                    }
                }

                TempData["SuccessMessage"] = "Record Saved Successfully";
                return RedirectToAction("Consignors");
            }
            return View();
        }

        public async System.Threading.Tasks.Task<ActionResult> DeleteConsignor(int id)
        {
            using (var httpClient = new HttpClient())
            {

                using (var response = await httpClient.DeleteAsync("http://localhost:17165/api/Master/DeleteConsignor?id=" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();

                }
            }

            return RedirectToAction("Consignors");
        }
    }
}

UI/Views/Consignee/Consignee.cshtml
@model IEnumerable<UI.Models.Recievers>

@{
    ViewBag.Title = "Consignee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<header class="page-header">
    <h2>Consignees</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-users"></i>
                </a>
            </li>
            <li><span>Consignee</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>


<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <a href="@Url.Action("CreateConsignor", "Master")" class="btn btn-primary">
                <i class="fas fa-plus-square"></i> Create
            </a>
        </div>
    </div>
</div>

<hr />


<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">Consignees</h2>
            </header>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.ConsigneeID)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Address1)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Address2)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.State)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.City)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pincode)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.MobileNo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ConsignorGst)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ConsigneeID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Address1)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Address2)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.State)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.City)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Pincode)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MobileNo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ConsignorGst)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </section>

    </div>

</div>

UI/Views/Consignee/CreateConsignee.cshtml
@model UI.Models.Recievers

@{
    ViewBag.Title = "CreateConsignee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<header class="page-header">
    <h2>Consignees</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-users"></i>
                </a>
            </li>
            <li><span>Consignees</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>


<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">Consignee</h2>
            </header>
            <div class="panel-body">

             @using (Html.BeginForm())
             {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @*<div class="form-group">
                            @Html.LabelFor(model => model.ConsigneeID, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.ConsigneeID, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ConsigneeID, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Pincode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Pincode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Pincode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ConsignorGst, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ConsignorGst, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ConsignorGst, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
             }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>


            </div>
        </section>
    </div>
</div>

UI/Views/Consignee/EditConsignee.cshtml
@model UI.Models.Recievers

@{
    ViewBag.Title = "EditConsignee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="page-header">
    <h2>Consignees</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-users"></i>
                </a>
            </li>
            <li><span>Consignees</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">Consignees</h2>
            </header>
            <div class="panel-body">

              @using (Html.BeginForm())
              {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Pincode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Pincode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Pincode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ConsignorGst, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ConsignorGst, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ConsignorGst, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
              }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

            </div>
        </section>
    </div>
</div>